language: python
python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypi"
  # command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: nosetests